/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DealershipRouteImport } from './routes/dealership'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LegalDisclosuresRouteImport } from './routes/legal/disclosures'
import { Route as OwnersIndexRouteImport } from './routes/owners/index'
import { Route as OwnersMaintenanceRouteImport } from './routes/owners/maintenance'
import { Route as OwnersResourcesRouteImport } from './routes/owners/resources'
import { Route as OwnersSavedRouteImport } from './routes/owners/saved'
import { Route as OwnersServiceRouteImport } from './routes/owners/service'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopFinanceRouteImport } from './routes/shop/finance'
import { Route as ShopInventoryRouteImport } from './routes/shop/inventory'
import { Route as ShopOffersRouteImport } from './routes/shop/offers'
import { Route as ShopTestDriveRouteImport } from './routes/shop/test-drive'
import { Route as ShopTradeInRouteImport } from './routes/shop/trade-in'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles/index'
import { Route as VehiclesCompareRouteImport } from './routes/vehicles/compare'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as VehiclesSlugIndexRouteImport } from './routes/vehicles/$slug/index'
import { Route as VehiclesSlugConfigureRouteImport } from './routes/vehicles/$slug/configure'
import { Route as ApiV1ConfigurationsIndexRouteImport } from './routes/api/v1/configurations/index'
import { Route as ApiV1ConfigurationsConfigurationIdRouteImport } from './routes/api/v1/configurations/$configurationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DealershipRoute = DealershipRouteImport.update({
  id: '/dealership',
  path: '/dealership',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclosuresRoute = LegalDisclosuresRouteImport.update({
  id: '/legal/disclosures',
  path: '/legal/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersIndexRoute = OwnersIndexRouteImport.update({
  id: '/owners/',
  path: '/owners/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersMaintenanceRoute = OwnersMaintenanceRouteImport.update({
  id: '/owners/maintenance',
  path: '/owners/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersResourcesRoute = OwnersResourcesRouteImport.update({
  id: '/owners/resources',
  path: '/owners/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersSavedRoute = OwnersSavedRouteImport.update({
  id: '/owners/saved',
  path: '/owners/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersServiceRoute = OwnersServiceRouteImport.update({
  id: '/owners/service',
  path: '/owners/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopFinanceRoute = ShopFinanceRouteImport.update({
  id: '/shop/finance',
  path: '/shop/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopInventoryRoute = ShopInventoryRouteImport.update({
  id: '/shop/inventory',
  path: '/shop/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopOffersRoute = ShopOffersRouteImport.update({
  id: '/shop/offers',
  path: '/shop/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopTestDriveRoute = ShopTestDriveRouteImport.update({
  id: '/shop/test-drive',
  path: '/shop/test-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopTradeInRoute = ShopTradeInRouteImport.update({
  id: '/shop/trade-in',
  path: '/shop/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesCompareRoute = VehiclesCompareRouteImport.update({
  id: '/vehicles/compare',
  path: '/vehicles/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesSlugIndexRoute = VehiclesSlugIndexRouteImport.update({
  id: '/vehicles/$slug/',
  path: '/vehicles/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesSlugConfigureRoute = VehiclesSlugConfigureRouteImport.update({
  id: '/vehicles/$slug/configure',
  path: '/vehicles/$slug/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ConfigurationsIndexRoute =
  ApiV1ConfigurationsIndexRouteImport.update({
    id: '/api/v1/configurations/',
    path: '/api/v1/configurations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1ConfigurationsConfigurationIdRoute =
  ApiV1ConfigurationsConfigurationIdRouteImport.update({
    id: '/api/v1/configurations/$configurationId',
    path: '/api/v1/configurations/$configurationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/dealership': typeof DealershipRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/api/health': typeof ApiHealthRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/owners/maintenance': typeof OwnersMaintenanceRoute
  '/owners/resources': typeof OwnersResourcesRoute
  '/owners/saved': typeof OwnersSavedRoute
  '/owners/service': typeof OwnersServiceRoute
  '/shop/finance': typeof ShopFinanceRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/offers': typeof ShopOffersRoute
  '/shop/test-drive': typeof ShopTestDriveRoute
  '/shop/trade-in': typeof ShopTradeInRoute
  '/vehicles/compare': typeof VehiclesCompareRoute
  '/owners/': typeof OwnersIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/vehicles/$slug/configure': typeof VehiclesSlugConfigureRoute
  '/vehicles/$slug/': typeof VehiclesSlugIndexRoute
  '/api/v1/configurations/$configurationId': typeof ApiV1ConfigurationsConfigurationIdRoute
  '/api/v1/configurations/': typeof ApiV1ConfigurationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/dealership': typeof DealershipRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/api/health': typeof ApiHealthRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/owners/maintenance': typeof OwnersMaintenanceRoute
  '/owners/resources': typeof OwnersResourcesRoute
  '/owners/saved': typeof OwnersSavedRoute
  '/owners/service': typeof OwnersServiceRoute
  '/shop/finance': typeof ShopFinanceRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/offers': typeof ShopOffersRoute
  '/shop/test-drive': typeof ShopTestDriveRoute
  '/shop/trade-in': typeof ShopTradeInRoute
  '/vehicles/compare': typeof VehiclesCompareRoute
  '/owners': typeof OwnersIndexRoute
  '/shop': typeof ShopIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/vehicles/$slug/configure': typeof VehiclesSlugConfigureRoute
  '/vehicles/$slug': typeof VehiclesSlugIndexRoute
  '/api/v1/configurations/$configurationId': typeof ApiV1ConfigurationsConfigurationIdRoute
  '/api/v1/configurations': typeof ApiV1ConfigurationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/dealership': typeof DealershipRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/api/health': typeof ApiHealthRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/owners/maintenance': typeof OwnersMaintenanceRoute
  '/owners/resources': typeof OwnersResourcesRoute
  '/owners/saved': typeof OwnersSavedRoute
  '/owners/service': typeof OwnersServiceRoute
  '/shop/finance': typeof ShopFinanceRoute
  '/shop/inventory': typeof ShopInventoryRoute
  '/shop/offers': typeof ShopOffersRoute
  '/shop/test-drive': typeof ShopTestDriveRoute
  '/shop/trade-in': typeof ShopTradeInRoute
  '/vehicles/compare': typeof VehiclesCompareRoute
  '/owners/': typeof OwnersIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/vehicles/$slug/configure': typeof VehiclesSlugConfigureRoute
  '/vehicles/$slug/': typeof VehiclesSlugIndexRoute
  '/api/v1/configurations/$configurationId': typeof ApiV1ConfigurationsConfigurationIdRoute
  '/api/v1/configurations/': typeof ApiV1ConfigurationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/account'
    | '/dealership'
    | '/login'
    | '/privacy'
    | '/api/health'
    | '/legal/disclosures'
    | '/owners/maintenance'
    | '/owners/resources'
    | '/owners/saved'
    | '/owners/service'
    | '/shop/finance'
    | '/shop/inventory'
    | '/shop/offers'
    | '/shop/test-drive'
    | '/shop/trade-in'
    | '/vehicles/compare'
    | '/owners/'
    | '/shop/'
    | '/vehicles/'
    | '/api/auth/$'
    | '/vehicles/$slug/configure'
    | '/vehicles/$slug/'
    | '/api/v1/configurations/$configurationId'
    | '/api/v1/configurations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/account'
    | '/dealership'
    | '/login'
    | '/privacy'
    | '/api/health'
    | '/legal/disclosures'
    | '/owners/maintenance'
    | '/owners/resources'
    | '/owners/saved'
    | '/owners/service'
    | '/shop/finance'
    | '/shop/inventory'
    | '/shop/offers'
    | '/shop/test-drive'
    | '/shop/trade-in'
    | '/vehicles/compare'
    | '/owners'
    | '/shop'
    | '/vehicles'
    | '/api/auth/$'
    | '/vehicles/$slug/configure'
    | '/vehicles/$slug'
    | '/api/v1/configurations/$configurationId'
    | '/api/v1/configurations'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/account'
    | '/dealership'
    | '/login'
    | '/privacy'
    | '/api/health'
    | '/legal/disclosures'
    | '/owners/maintenance'
    | '/owners/resources'
    | '/owners/saved'
    | '/owners/service'
    | '/shop/finance'
    | '/shop/inventory'
    | '/shop/offers'
    | '/shop/test-drive'
    | '/shop/trade-in'
    | '/vehicles/compare'
    | '/owners/'
    | '/shop/'
    | '/vehicles/'
    | '/api/auth/$'
    | '/vehicles/$slug/configure'
    | '/vehicles/$slug/'
    | '/api/v1/configurations/$configurationId'
    | '/api/v1/configurations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AccountRoute: typeof AccountRoute
  DealershipRoute: typeof DealershipRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiHealthRoute: typeof ApiHealthRoute
  LegalDisclosuresRoute: typeof LegalDisclosuresRoute
  OwnersMaintenanceRoute: typeof OwnersMaintenanceRoute
  OwnersResourcesRoute: typeof OwnersResourcesRoute
  OwnersSavedRoute: typeof OwnersSavedRoute
  OwnersServiceRoute: typeof OwnersServiceRoute
  ShopFinanceRoute: typeof ShopFinanceRoute
  ShopInventoryRoute: typeof ShopInventoryRoute
  ShopOffersRoute: typeof ShopOffersRoute
  ShopTestDriveRoute: typeof ShopTestDriveRoute
  ShopTradeInRoute: typeof ShopTradeInRoute
  VehiclesCompareRoute: typeof VehiclesCompareRoute
  OwnersIndexRoute: typeof OwnersIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  VehiclesSlugConfigureRoute: typeof VehiclesSlugConfigureRoute
  VehiclesSlugIndexRoute: typeof VehiclesSlugIndexRoute
  ApiV1ConfigurationsConfigurationIdRoute: typeof ApiV1ConfigurationsConfigurationIdRoute
  ApiV1ConfigurationsIndexRoute: typeof ApiV1ConfigurationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealership': {
      id: '/dealership'
      path: '/dealership'
      fullPath: '/dealership'
      preLoaderRoute: typeof DealershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclosures': {
      id: '/legal/disclosures'
      path: '/legal/disclosures'
      fullPath: '/legal/disclosures'
      preLoaderRoute: typeof LegalDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/': {
      id: '/owners/'
      path: '/owners'
      fullPath: '/owners/'
      preLoaderRoute: typeof OwnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/maintenance': {
      id: '/owners/maintenance'
      path: '/owners/maintenance'
      fullPath: '/owners/maintenance'
      preLoaderRoute: typeof OwnersMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/resources': {
      id: '/owners/resources'
      path: '/owners/resources'
      fullPath: '/owners/resources'
      preLoaderRoute: typeof OwnersResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/saved': {
      id: '/owners/saved'
      path: '/owners/saved'
      fullPath: '/owners/saved'
      preLoaderRoute: typeof OwnersSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners/service': {
      id: '/owners/service'
      path: '/owners/service'
      fullPath: '/owners/service'
      preLoaderRoute: typeof OwnersServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/finance': {
      id: '/shop/finance'
      path: '/shop/finance'
      fullPath: '/shop/finance'
      preLoaderRoute: typeof ShopFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/inventory': {
      id: '/shop/inventory'
      path: '/shop/inventory'
      fullPath: '/shop/inventory'
      preLoaderRoute: typeof ShopInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/offers': {
      id: '/shop/offers'
      path: '/shop/offers'
      fullPath: '/shop/offers'
      preLoaderRoute: typeof ShopOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/test-drive': {
      id: '/shop/test-drive'
      path: '/shop/test-drive'
      fullPath: '/shop/test-drive'
      preLoaderRoute: typeof ShopTestDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/trade-in': {
      id: '/shop/trade-in'
      path: '/shop/trade-in'
      fullPath: '/shop/trade-in'
      preLoaderRoute: typeof ShopTradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/compare': {
      id: '/vehicles/compare'
      path: '/vehicles/compare'
      fullPath: '/vehicles/compare'
      preLoaderRoute: typeof VehiclesCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$slug/': {
      id: '/vehicles/$slug/'
      path: '/vehicles/$slug'
      fullPath: '/vehicles/$slug/'
      preLoaderRoute: typeof VehiclesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$slug/configure': {
      id: '/vehicles/$slug/configure'
      path: '/vehicles/$slug/configure'
      fullPath: '/vehicles/$slug/configure'
      preLoaderRoute: typeof VehiclesSlugConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/configurations/': {
      id: '/api/v1/configurations/'
      path: '/api/v1/configurations'
      fullPath: '/api/v1/configurations/'
      preLoaderRoute: typeof ApiV1ConfigurationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/configurations/$configurationId': {
      id: '/api/v1/configurations/$configurationId'
      path: '/api/v1/configurations/$configurationId'
      fullPath: '/api/v1/configurations/$configurationId'
      preLoaderRoute: typeof ApiV1ConfigurationsConfigurationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AccountRoute: AccountRoute,
  DealershipRoute: DealershipRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ApiHealthRoute: ApiHealthRoute,
  LegalDisclosuresRoute: LegalDisclosuresRoute,
  OwnersMaintenanceRoute: OwnersMaintenanceRoute,
  OwnersResourcesRoute: OwnersResourcesRoute,
  OwnersSavedRoute: OwnersSavedRoute,
  OwnersServiceRoute: OwnersServiceRoute,
  ShopFinanceRoute: ShopFinanceRoute,
  ShopInventoryRoute: ShopInventoryRoute,
  ShopOffersRoute: ShopOffersRoute,
  ShopTestDriveRoute: ShopTestDriveRoute,
  ShopTradeInRoute: ShopTradeInRoute,
  VehiclesCompareRoute: VehiclesCompareRoute,
  OwnersIndexRoute: OwnersIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  VehiclesSlugConfigureRoute: VehiclesSlugConfigureRoute,
  VehiclesSlugIndexRoute: VehiclesSlugIndexRoute,
  ApiV1ConfigurationsConfigurationIdRoute:
    ApiV1ConfigurationsConfigurationIdRoute,
  ApiV1ConfigurationsIndexRoute: ApiV1ConfigurationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
